/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.aggregate.adtech.worker.model.serdes;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth8.assertThat;
import static org.junit.Assert.assertFalse;

import com.google.acai.Acai;
import com.google.aggregate.adtech.worker.model.SharedInfo;
import com.google.inject.AbstractModule;
import java.time.Instant;
import java.util.Optional;
import javax.inject.Inject;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class SharedInfoSerdesTest {

  // FIXED_TIME = Jan 01 2021 00:00:00 GMT+0000
  private static final Instant FIXED_TIME = Instant.ofEpochSecond(1609459200);

  private static final String ATTRIBUTION_REPORTING_API = "attribution-reporting";

  private static final String VERSION_ZERO_DOT_ONE = "0.1";

  private static final String DESTINATION_CHROME_GOLDEN_REPORT = "https://conversion.test";

  private static final String REPORTING_ORIGIN_CHROME_GOLDEN_REPORT = "https://report.test";

  private static final String SAMPLE_REPORT_ID = "129470d5-3095-4385-81e2-08f5a9063549";

  @Rule public final Acai acai = new Acai(TestEnv.class);

  @Inject private SharedInfoSerdes sharedInfoSerdes;

  private SharedInfo sharedInfo;

  private SharedInfo sharedInfoWithoutOptionals;

  private SharedInfo sharedInfoWithOptionalsWithoutPrivacyBudgetKey;

  private SharedInfo sharedInfoWithAllOptionals;

  private SharedInfo sharedInfoWithoutDebugMode;

  private SharedInfo sharedInfoWithChromeGoldenReport;

  @Before
  public void setUp() {
    sharedInfo =
        SharedInfo.builder()
            .setVersion("")
            .setReportId(SAMPLE_REPORT_ID)
            .setScheduledReportTime(FIXED_TIME)
            .setReportingOrigin("bar.com")
            .setPrivacyBudgetKey("foo")
            .setReportDebugMode(true)
            .build();

    sharedInfoWithoutOptionals =
        SharedInfo.builder()
            .setVersion("")
            .setReportId(SAMPLE_REPORT_ID)
            .setScheduledReportTime(FIXED_TIME)
            .setReportingOrigin("origin.com")
            .build();

    sharedInfoWithOptionalsWithoutPrivacyBudgetKey =
        SharedInfo.builder()
            .setVersion(VERSION_ZERO_DOT_ONE)
            .setApi(ATTRIBUTION_REPORTING_API)
            .setReportId(SAMPLE_REPORT_ID)
            .setScheduledReportTime(FIXED_TIME)
            .setDestination("destination.com")
            .setReportingOrigin("origin.com")
            .setSourceRegistrationTime(FIXED_TIME)
            .build();

    sharedInfoWithAllOptionals =
        SharedInfo.builder()
            .setVersion(VERSION_ZERO_DOT_ONE)
            .setApi(ATTRIBUTION_REPORTING_API)
            .setReportId(SAMPLE_REPORT_ID)
            .setPrivacyBudgetKey("test_privacy_budget_key")
            .setScheduledReportTime(FIXED_TIME)
            .setDestination("destination.com")
            .setReportingOrigin("origin.com")
            .setSourceRegistrationTime(FIXED_TIME)
            .build();

    sharedInfoWithoutDebugMode =
        SharedInfo.builder()
            .setVersion("")
            .setReportId(SAMPLE_REPORT_ID)
            .setScheduledReportTime(FIXED_TIME)
            .setReportingOrigin("bar.com")
            .setPrivacyBudgetKey("foo")
            .build();

    sharedInfoWithChromeGoldenReport =
        SharedInfo.builder()
            .setVersion(VERSION_ZERO_DOT_ONE)
            .setApi(ATTRIBUTION_REPORTING_API)
            .setReportId("21abd97f-73e8-4b88-9389-a9fee6abda5e")
            .setDestination(DESTINATION_CHROME_GOLDEN_REPORT)
            .setReportingOrigin(REPORTING_ORIGIN_CHROME_GOLDEN_REPORT)
            .setScheduledReportTime(Instant.ofEpochSecond(1234486400))
            .setSourceRegistrationTime(Instant.ofEpochSecond(1234483200))
            .setReportDebugMode(true)
            .build();
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo1() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\",\""
            + "report_id\":\"cbc6fb00-c946-4eb6-a401-aac133f7f0b8\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673933\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("cbc6fb00-c946-4eb6-a401-aac133f7f0b8")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673933))
                .setReportDebugMode(true)
                .build());
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo2() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\","
            + "\"report_id\":\"3076f70b-3704-4318-8ce0-068bd599d5aa\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673973\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("3076f70b-3704-4318-8ce0-068bd599d5aa")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673973))
                .setReportDebugMode(true)
                .build());
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo3() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\","
            + "\"report_id\":\"b92692f5-5d8f-4c98-b4de-ecbfc34ac9bc\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673973\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("b92692f5-5d8f-4c98-b4de-ecbfc34ac9bc")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673973))
                .setReportDebugMode(true)
                .build());
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo4() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\","
            + "\"report_id\":\"f7533d07-04df-4299-9938-73948b33c2c4\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673974\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("f7533d07-04df-4299-9938-73948b33c2c4")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673974))
                .setReportDebugMode(true)
                .build());
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo5() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\","
            + "\"report_id\":\"5a5521f4-575b-45c5-93f1-8ae1449cc81d\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673974\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("5a5521f4-575b-45c5-93f1-8ae1449cc81d")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673974))
                .setReportDebugMode(true)
                .build());
  }

  /** Deserialize from a sample shared_info generated by Chrome */
  @Test
  public void testDeserializeSharedInfoFromChrome_sharedInfo6() {
    String sharedInfoJsonString =
        "{\"debug_mode\":\"enabled\",\"privacy_budget_key\":\"test_privacy_budget_key\","
            + "\"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\",\"reporting_origin\":"
            + "\"https://example.com\",\"scheduled_report_time\":\"1648673974\","
            + "\"version\":\"\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("test_privacy_budget_key")
                .setVersion("")
                .setReportId("129470d5-3095-4385-81e2-08f5a9063549")
                .setReportingOrigin("https://example.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1648673974))
                .setReportDebugMode(true)
                .build());
  }

  @Test
  public void testDeserializesFromStringWithUnknownFields() {
    String sharedInfoJsonString =
        "{\"version\": \"\", \"debug_mode\":\"enabled\", \"privacy_budget_key\":\"foo\","
            + " \"scheduled_report_time\": \"1609459200\", \"reporting_origin\": \"bar.com\","
            + " \"unknown_field\": \"fizzbuzz\","
            + " \"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized).hasValue(sharedInfo);
  }

  @Test
  public void testDeserializeFromSharedInfoJsonWithOutOptionals() {
    String sharedInfoJsonString =
        "{\"version\": \"\", \"scheduled_report_time\": \"1609459200\","
            + " \"unknown_field\": \"fizzbuzz\", \"reporting_origin\":\"origin.com\","
            + " \"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized).hasValue(sharedInfoWithoutOptionals);
  }

  @Test
  public void testDeserializeFromSharedInfoJsonWithOptionalsWithoutPrivacyBudgetKey() {
    String sharedInfoJsonString =
        "{\"version\": \"0.1\", \"api\":\"attribution-reporting\", \"scheduled_report_time\":"
            + " \"1609459200\",  \"unknown_field\": \"fizzbuzz\", \"attribution_destination\":"
            + " \"destination.com\", \"reporting_origin\":\"origin.com\","
            + " \"source_registration_time\":\"1609459200\","
            + " \"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\" }";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized).hasValue(sharedInfoWithOptionalsWithoutPrivacyBudgetKey);
  }

  @Test
  public void testDeserializeFromSharedInfoJsonWithAllOptionals() {
    String sharedInfoJsonString =
        "{\"version\": \"0.1\", \"api\":\"attribution-reporting\", \"scheduled_report_time\":"
            + " \"1609459200\",  \"unknown_field\": \"fizzbuzz\", \"attribution_destination\":"
            + " \"destination.com\", \"reporting_origin\":\"origin.com\","
            + " \"source_registration_time\":\"1609459200\",  \"privacy_budget_key\":"
            + " \"test_privacy_budget_key\", \"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\""
            + " }";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized).hasValue(sharedInfoWithAllOptionals);
  }

  /** Deserialize from a sample shared_info generated by Chrome without debug mode */
  @Test
  public void testDeserializeFromStringWithoutDebugMode() {
    String sharedInfoJsonString =
        "{\"version\": \"\", \"privacy_budget_key\":\"foo\", \"scheduled_report_time\":"
            + " \"1609459200\", \"reporting_origin\": \"bar.com\", \"unknown_field\": \"fizzbuzz\","
            + " \"report_id\":\"129470d5-3095-4385-81e2-08f5a9063549\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized)
        .hasValue(
            SharedInfo.builder()
                .setPrivacyBudgetKey("foo")
                .setVersion("")
                .setReportId("129470d5-3095-4385-81e2-08f5a9063549")
                .setReportingOrigin("bar.com")
                .setScheduledReportTime(Instant.ofEpochSecond(1609459200))
                .build());
  }

  @Test
  public void testSerializeAndDeserialize() {
    // No setup

    String serialized = sharedInfoSerdes.reverse().convert(Optional.of(sharedInfo));
    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(serialized);

    assertThat(deserialized).hasValue(sharedInfo);
  }

  /** Deserialize from a sample shared_info generated by Chrome without debug mode */
  @Test
  public void testSerializeAndDeserializeWithoutDebugMode() {
    // No setup

    String serialized = sharedInfoSerdes.reverse().convert(Optional.of(sharedInfoWithoutDebugMode));
    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(serialized);

    assertThat(deserialized).hasValue(sharedInfoWithoutDebugMode);
  }

  /**
   * Test if setting debug_mode false in SharedInfo object doesn't add "debug_mode" string to
   * serialized SharedInfo string
   */
  @Test
  public void testSerializeSharedInfoDebugModeDisabled() {
    // No setup
    SharedInfo sharedInfoDebugModeDisabled =
        SharedInfo.builder()
            .setVersion("")
            .setReportId(SAMPLE_REPORT_ID)
            .setScheduledReportTime(FIXED_TIME)
            .setReportingOrigin("bar.com")
            .setPrivacyBudgetKey("foo")
            .setReportDebugMode(false)
            .build();

    String serialized =
        sharedInfoSerdes.reverse().convert(Optional.ofNullable(sharedInfoDebugModeDisabled));

    assertFalse(serialized.contains("debug_mode"));
  }

  /** Serialize share-info for simulation. Check @JsonIgnore and @JsonProperty setting correctly */
  @Test
  public void testSerializeSharedInfoIgnoreField() {
    // No setup

    String serialized = sharedInfoSerdes.reverse().convert(Optional.ofNullable(sharedInfo));

    assertFalse(serialized.contains("reportDebugMode"));
  }

  @Test
  public void testReturnsEmptyOptionalForBadInput() {
    String badInput = "invalid string";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(badInput);

    assertThat(deserialized).isEmpty();
  }

  @Test
  public void testReturnsEmptyStringForEmptyOptional() throws Exception {
    // No setup

    String serialized = sharedInfoSerdes.reverse().convert(Optional.empty());

    assertThat(serialized.isEmpty()).isTrue();
  }

  /*
   * Test based on Chrome Aggregatable Golden Report
   * https://source.chromium.org/chromium/chromium/src/+/main:content/test/data/attribution_reporting/aggregatable_report_goldens/latest/report_1.json
   * */
  @Test
  public void testDeserializeOnChromeAggregatableGoldenReport() {
    String sharedInfoJsonString =
        "{\"api\":\"attribution-reporting\",\"attribution_destination\":\"https://conversion.test\","
            + "\"debug_mode\":\"enabled\",\"report_id\":\"21abd97f-73e8-4b88-9389-a9fee6abda5e\","
            + "\"reporting_origin\":\"https://report.test\",\"scheduled_report_time\":\"1234486400\","
            + "\"source_registration_time\":\"1234483200\",\"version\":\"0.1\"}";

    Optional<SharedInfo> deserialized = sharedInfoSerdes.convert(sharedInfoJsonString);

    assertThat(deserialized).hasValue(sharedInfoWithChromeGoldenReport);
  }

  private static final class TestEnv extends AbstractModule {}
}
