#!/bin/bash

set -o pipefail
set -o errexit
set -o xtrace

BAZEL_PATH=
usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --bazel-symlink-path <dir>    Set path for bazel symlink. Default: not set
USAGE
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bazel-symlink-path)
      BAZEL_PATH=$2
      shift
      shift
      ;;
    -h | --help)
      usage 0
      break
      ;;
    *)
      usage
      break
      ;;
  esac
done

function install_bazelisk() {
  go install github.com/bazelbuild/bazelisk@v1.14.0
  BAZELISK="$(go env GOPATH)"/bin/bazelisk
  if [[ -n ${BAZEL_PATH} ]] && [[ -d ${BAZEL_PATH} ]]; then
    ln -s ${BAZELISK} ${BAZEL_PATH}/bazel
  fi
  # install the specified version of bazel
  USE_BAZEL_VERSION="$(cat /scripts/.bazelversion)"
  export USE_BAZEL_VERSION
  "${BAZELISK}" version
}

install_bazelisk
